ASOworx: ASO_Display Class Reference
ASO_Display Class Reference
Static Public Member Functions
static factory ($backend, $config=array())
static display ($view, $data=array())
Detailed Description
Definition at line 43 of file Display.php.
Member Function Documentation
static display ($ view, $ data = array()) [static]
Tells the display backend to show its display
Parameters:
array $view The view to display
array $data The data to be used in the view
Returns:
void
Definition at line 83 of file Display.php.
Referenced by ASO_Dispatch::_dispatch(), and ASO_Dispatch::run().
static factory ($ backend, $ config = array()) [static]
Creates the display adapter using the backend passed.
Parameters:
string $backend The name of the backend to use.
array $config The configuration to pass to the backend.
Returns:
void
Definition at line 58 of file Display.php.
Referenced by ASO_Dispatch::__construct().
The documentation for this class was generated from the following file:
lib/ASO/Display.php