ASOworx: ASO_Db_Abstract Class Reference
ASO_Db_Abstract Class Reference
Public Member Functions
__construct ($config=array())
query ($query_string, $no_debug=false)
Data Fields
$query = ""
$querycount = 0
$querytimes = array()
$querylist = array()
Protected Attributes
$_config = array()
$_connection = null
$_queryid = null
Detailed Description
Definition at line 43 of file Abstract.php.
Constructor & Destructor Documentation
__construct ($ config = array())
Constructor for the class. Just sets some values for other functions.
Parameters:
array $config The configuration to use for connection
Definition at line 92 of file Abstract.php.
Member Function Documentation
query ($ query_string, $ no_debug = false)
Queries the database. Runs through the sub-class's _query() function.
Parameters:
string $query_string The query string to run
boolean $no_debug Tells the function if it should record the query in the debug variables.
Definition at line 107 of file Abstract.php.
Referenced by ASO_Db_MySQL::getAll(), ASO_Db_MySQL::insert(), ASO_Db_MySQL::queryFetch(), ASO_Db_MySQL::queryFetchAll(), ASO_Db_MySQL::replace(), and ASO_Db_MySQL::update().
The documentation for this class was generated from the following file:
lib/ASO/Db/Abstract.php