ASOworx: ASO_Controller Class Reference
ASO_Controller Class Reference
Public Member Functions
__construct ($config)
completeDispatch ()
redirect ($location)
logException ($e)
emailException ($e)
Data Fields
$sess = array()
$defaultMethod = 'main'
Protected Member Functions
_setEnvironment ()
_loadPlugins ()
_setup ()
Protected Attributes
$config = array()
$input = array()
$db = array()
$error = null
$_session = null
$baseURL = ''
Detailed Description
Definition at line 63 of file Controller.php.
Constructor & Destructor Documentation
__construct ($ config)
Constructor
Sets up the controller environment at the same time, including input filtering and session access.
Parameters:
array $config System configuration for setting up environment
Definition at line 121 of file Controller.php.
Member Function Documentation
_loadPlugins () [protected]
Loads and initializes plugins in the app directory
Returns:
void
Definition at line 199 of file Controller.php.
Referenced by __construct().
_setEnvironment () [protected]
Ensures a stable execution environment
Returns:
void
Definition at line 187 of file Controller.php.
Referenced by __construct().
_setup () [protected]
Default setup function
Returns:
void
Definition at line 222 of file Controller.php.
Referenced by __construct().
completeDispatch ()
Runs any completion tasks after the controller event is dispatched
Returns:
void
Definition at line 161 of file Controller.php.
emailException ($ e)
Default callback for emailing runtime exceptions.
Override this method in a subclass of ASO_Controller to change the default behavior.
Parameters:
Exception $e The exception that was thrown at runtime
Definition at line 268 of file Controller.php.
logException ($ e)
Default callback for logging runtime exceptions.
Override this method in a subclass of ASO_Controller to log this error to someplace other than var/log/exceptions.log.
Parameters:
Exception $e The exception that was thrown at runtime
Definition at line 233 of file Controller.php.
redirect ($ location)
Redirects to another location.
Parameters:
string $location The location to redirect to
Returns:
void
Definition at line 174 of file Controller.php.
The documentation for this class was generated from the following file:
lib/ASO/Controller.php