ASOworx: ASO_Dispatch Class Reference
ASO_Dispatch Class Reference
Public Member Functions
__construct ()
throwExceptions ($flag=null)
logExceptions ($flag=null)
emailExceptions ($flag=null, $emailAddress= 'nobody')
run ()
Data Fields
$config = array()
$action = ''
$method = ''
$extra = null
Protected Member Functions
_dispatch ()
_splitURI ()
_loadRouting ()
Protected Attributes
$_baseURL = null
$_throwExceptions = false
$_logExceptions = false
$_emailExceptions = false
$_defaultAction = 'index'
Detailed Description
Definition at line 62 of file Dispatch.php.
Constructor & Destructor Documentation
__construct ()
Constructor
Returns:
void
Definition at line 124 of file Dispatch.php.
Member Function Documentation
_dispatch () [protected]
Dispatches an HTTP request to its assigned controller
Exceptions:
ASO_Dispatch_Exception
Returns:
void
Definition at line 265 of file Dispatch.php.
Referenced by run().
_loadRouting () [protected]
Loads routing from app/Routing.php Note: routes were previously stored in app/Config.php but moved so that they could be versioned.
Returns:
void
Definition at line 398 of file Dispatch.php.
Referenced by _dispatch().
_splitURI () [protected]
Splits the HTTP request URI into action, method, extra data. Applies routing.
Returns:
void
Definition at line 318 of file Dispatch.php.
Referenced by _dispatch().
emailExceptions ($ flag = null, $ emailAddress = 'nobody')
Sets the emailExceptions flag and retreives the current status.
By default, exceptions are caught by the ASO_Dispatch class. Enabling this flag will additionally email them to an administrator (or whoever's email is passed in as the 2nd parameter).
Parameters:
boolean $flag
Returns:
void
Definition at line 188 of file Dispatch.php.
Referenced by run().
logExceptions ($ flag = null)
Sets the logExceptions flag and retreives the current status.
By default, exceptions are caught by the ASO_Dispatch class. Enabling this flag will additionally log them to a file defined by $CONFIG['exception_log'] (in app/Config.php).
Parameters:
boolean $flag
Returns:
void
Definition at line 167 of file Dispatch.php.
Referenced by run().
run ()
Starts execution of the ASOworx framework.
Exceptions:
ASO_Exception
Returns:
void
Definition at line 205 of file Dispatch.php.
throwExceptions ($ flag = null)
Sets the throwExceptions flag and retreives the current status.
By default, exceptions are caught by the ASO_Dispatch class. Enabling this flag will allow them to pass back to the caller.
Parameters:
boolean $flag
Returns:
void
Definition at line 146 of file Dispatch.php.
Referenced by _dispatch(), and run().
The documentation for this class was generated from the following file:
lib/ASO/Dispatch.php