ASOworx: ASO_Db_MySQL Class Reference
ASO_Db_MySQL Class Reference
Public Member Functions
connect ()
close ()
queryFetch ($query_string="", $no_debug=0)
queryFetchAll ($query_string="", $no_debug=0)
insert ($table="", $data=array())
replace ($table="", $data=array())
update ($table="", $data=array(), $id_field, $id)
fetch_array ($queryid=-1)
fetch_assoc ($queryid=-1)
data_seek ($queryid, $row)
num_rows ($queryid=-1)
affected_rows ($queryid=-1)
insert_id ()
getAll ($table, $limit=0, $offset=0)
getByPage ($table, $limit=0, $page=0, $where= '')
get ($table, $where)
enum_values ($table, $field)
unique_values ($table, $field)
__toString ()
Protected Member Functions
_query ($query_string="", $no_debug=false)
Detailed Description
Definition at line 43 of file MySQL.php.
Member Function Documentation
__toString ()
Returns the string representation of the object
Returns:
string
Definition at line 394 of file MySQL.php.
_query ($ query_string = "", $ no_debug = false) [protected]
Wrapper for mysql_query(). Expected to be called from _query()
Parameters:
string $query_string The query string to run
boolean $no_debug Tells the function if it should record the query in the debug variables.
Returns:
void
Definition at line 92 of file MySQL.php.
affected_rows ($ queryid = -1)
Wrapper for mysql_affected_rows()
Parameters:
resource $connectid The connection ID to use for this operation
Returns:
int The number of affected rows
Definition at line 273 of file MySQL.php.
close ()
Wrapper for mysql_close()
Returns:
void
Definition at line 79 of file MySQL.php.
connect ()
Connects to the defined server and selects the defined database.
Do not use directly. query() will connect the database if it has not been connected already. This method allows the database layer to be instantiated on every page without neccessarily requiring a database connection on each page.
Returns:
void
Definition at line 55 of file MySQL.php.
data_seek ($ queryid, $ row)
Wrapper for mysql_data_seek()
Parameters:
resource $queryid The query ID to use for this operation
integer $row Thw row to seek data to
Returns:
resource The query ID
Definition at line 247 of file MySQL.php.
enum_values ($ table, $ field)
Grab the enumeration/set values from a table for a specific field.
Parameters:
string $table The name of the table to pull from
string $field The field to pull from
Returns:
array The values that make up the enumeration
Definition at line 367 of file MySQL.php.
fetch_array ($ queryid = -1)
Wrapper for mysql_fetch_array().
Parameters:
resource $queryid The query ID to use for this operation
Returns:
array The data from the current row.
Definition at line 220 of file MySQL.php.
Referenced by getAll().
fetch_assoc ($ queryid = -1)
Wrapper for mysql_fetch_assoc()
Parameters:
resource $queryid The query ID to use for this operation
Returns:
array The data from the current row
Definition at line 233 of file MySQL.php.
Referenced by queryFetch(), and queryFetchAll().
get ($ table, $ where)
Grab an entry from a table.
Parameters:
string $table The name of the table to pull from
string $id A WHERE condition to match
Returns:
array The item from the table
Definition at line 356 of file MySQL.php.
getAll ($ table, $ limit = 0, $ offset = 0)
Grab all the data from a table. Makes for easy coding.
Parameters:
string $table The name of the table to pull from
int $limit The number of rows to limit the results to
int $offset The offset of the row to start from
Returns:
array The data from the table
Definition at line 297 of file MySQL.php.
Referenced by getByPage().
getByPage ($ table, $ limit = 0, $ page = 0, $ where = '')
Paginate data from the table.
Parameters:
string $table The name of the table to pull from
int $limit The number of rows per page
int $page The page we're on right now
Returns:
array The data from the table and the total pages there are
Definition at line 332 of file MySQL.php.
insert ($ table = "", $ data = array())
Inserts an array of data into a table
Parameters:
string $table The table to insert into
array $data The data to insert with keys as field names
Returns:
resource The ID of the query
Definition at line 149 of file MySQL.php.
insert_id ()
Wrapper for mysql_insert_id()
Returns:
int The id of the last inserted row
Definition at line 285 of file MySQL.php.
num_rows ($ queryid = -1)
Wrapper for mysql_num_rows()
Parameters:
resource $queryid The query ID to use for this operation
Returns:
int The number of selected rows
Definition at line 260 of file MySQL.php.
queryFetch ($ query_string = "", $ no_debug = 0)
Querys the db and gets one row.
Parameters:
string $query_string The query string to run
integer $no_debug Tells the function if it should record the query in the debug variables.
Returns:
array The 1st row of the query
Definition at line 106 of file MySQL.php.
Referenced by enum_values(), get(), and getByPage().
queryFetchAll ($ query_string = "", $ no_debug = 0)
Querys the db and gets all rows.
Parameters:
string $query_string The query string to run
integer $no_debug Tells the function if it should record the query in the debug variables.
Returns:
array An array of all rows of the query
Definition at line 126 of file MySQL.php.
Referenced by unique_values().
replace ($ table = "", $ data = array())
Replaces an array of data in a table or creates a new row
Parameters:
string $table The table to replace info
array $data The data to replace with keys as field names
Returns:
resource The ID of the query
Definition at line 174 of file MySQL.php.
unique_values ($ table, $ field)
Grab the unique values from a table for a specific field.
Parameters:
string $table The name of the table to pull from
string $field The field to pull from
Returns:
array The unique values that make up the field
Definition at line 380 of file MySQL.php.
update ($ table = "", $ data = array(), $ id_field, $ id)
Updates a row of data in a table
Parameters:
string $table The table to update
array $data The data to update to with keys as field names
string $id_field The field on which to match the row to update
mixed $id The id of that field
Returns:
resource The ID of the query
Definition at line 201 of file MySQL.php.
The documentation for this class was generated from the following file:
lib/ASO/Db/MySQL.php