ASOworx: ASO_Input Class Reference
ASO_Input Class Reference
Static Public Member Functions
static & filterInput ()
static cleanKey ($key)
static cleanValue ($val)
static cleanerValue ($val)
Detailed Description
Definition at line 43 of file Input.php.
Member Function Documentation
static cleanerValue ($ val) [static]
Cleans a value.
Handles more potential problems with input, such as XSS attacks.
Parameters:
mixed $val The value to clean
Returns:
string The cleaned value
Definition at line 163 of file Input.php.
static cleanKey ($ key) [static]
Handles some potential exploits with key names
Parameters:
string $key The key to clean
Returns:
string The cleaned key
Definition at line 115 of file Input.php.
Referenced by filterInput().
static cleanValue ($ val) [static]
Cleans a value
Handles most problems with SQL queries. Not neccessarily safe for input displayed back to other users.
Parameters:
mixed $val The value to clean
Returns:
string The cleaned value
Definition at line 138 of file Input.php.
Referenced by filterInput().
static& filterInput () [static]
Cleans input. Caches locally.
Takes all available $_GET, $_POST, and $_COOKIE input and reduces the chances of attacks and problems.
Also cleans the source IP address.
Returns:
array The cleaned input
Definition at line 61 of file Input.php.
Referenced by ASO_Controller::__construct(), and ASO_Display_Smarty::runDisplay().
The documentation for this class was generated from the following file:
lib/ASO/Input.php